[package]
name = "everybody_codes_2024_15"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
everybody_codes_util = { path = "../../util"}
bit-vec = "0.8.0"

[profile.dev]
opt-level = 3
